### ISSUE TITLE
Refactor to remove `cketh-minter` dependency

### ISSUE THREAD

**Issue by rvanasa** [internet-computer-protocol/evm-rpc-canister#243]
The current EVM RPC implementation reuses logic from a fork of the ckETH minter canister codebase. Removing this dependency would speed up development and improve testability of the canister.

**Comment by gregorydemay** [comment]
@rvanasa @THLO I started to look into a bit more details as to what this would entail and came up with the following rough plan (please feel free to comment/challenge any point or suggest alternative)

### Analysis
Usage of `cketh_common` in production code as of `04505cce853362ff1b8ea4954028333f54394419`

- `use cketh_common::eth_rpc_client::providers::RpcApi;` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/accounting.rs#L1)
- `use cketh_common::{ eth_rpc::{ into_nat, Block, FeeHistory, GetLogsParam, Hash, LogEntry, ProviderError, RpcError, SendRawTransactionResult, ValidationError, }, eth_rpc_client::{ providers::{RpcApi, RpcService}, requests::GetTransactionCountParams, EthRpcClient as CkEthRpcClient, MultiCallError, RpcConfig, RpcTransport, }, lifecycle::EthereumNetwork }` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/candid_rpc.rs#L4)
- `use cketh_common::eth_rpc_client::providers::{EthMainnetService, EthSepoliaService, L2MainnetService}`; [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/constants.rs#L1)
- `use cketh_common::eth_rpc::{HttpOutcallError, ProviderError, RpcError, ValidationError};` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/http.rs#L2)
- `use cketh_common::{ eth_rpc::{Block, FeeHistory, LogEntry, RpcError}, eth_rpc_client::{providers::RpcService, RpcConfig}, logs::INFO};` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/main.rs#L2)
- `use cketh_common::logs::{Log, Priority, Sort};`  [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/main.rs#L264)
- `use cketh_common::{ eth_rpc::ProviderError, eth_rpc_client::providers::{ EthMainnetService, EthSepoliaService, L2MainnetService, RpcApi, RpcService, }, logs::INFO};` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/providers.rs#L2)
- `use cketh_common::{ ::eth_rpc::RpcError, eth_rpc_client::providers::{ EthMainnetService, EthSepoliaService, L2MainnetService, RpcApi, RpcService, } };` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L2)
- `use cketh_common::{ address::Address, eth_rpc::Hash, eth_rpc::{into_nat, FixedSizeData, ValidationError}, numeric::BlockNumber };` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L521)
- `cketh_common::eth_rpc::BlockSpec` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L541)
- `cketh_common::eth_rpc::GetLogsParam` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L565)
- `cketh_common::eth_rpc::LogEntry` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L610)
- `cketh_common::eth_rpc_client::responses::TransactionReceipt` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L619)
- `cketh_common::eth_rpc::FeeHistoryParams` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L649)
- `cketh_common::eth_rpc_client::requests::GetTransactionCountParams` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/types.rs#L666)
- `use cketh_common::eth_rpc::ValidationError;` [here](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/04505cce853362ff1b8ea4954028333f54394419/src/validate.rs#L1)

### Overview

1. The main reason for using `cketh_common` is the usage of `EthRpcClient`, which contains all the logic for HTTPs outcalls (the EVM-RPC canisters method doing HTTPs outcalls, e.g., `eth_fee_history`, delegate to `EthRpcClient`).
2. From there follows the usage of the various parameter or response types used by `EthRpcClient`

### Rough Plan

1. Copy over all data types from `cketh_common` (e.g., `FeeHistory`, `LogEntry`, but not `EthRpcClient`), into this repository. As part of this effort I think it would be useful
    1. to have a dedicated crate for the Candid types used in the API of the EVM-RPC canister. The easiest would be for this crate to live in the same repo as the evm-rpc canister so that it's always in sync. 
    2. to have a dedicated crate for the type `CheckedAmountOf` (independent of the EVM-RPC canister) since this is also used by the ckETH minter (alternatively, integrate it into the `phantom_newtype` crate).
    3. We may want to have a clear separation between the types that are used for the candid interface (user/canister < > EVM-RPC) and the types that are used for the RPC communication (EVM-RPC <> Ethereum Json Provider), since the first are Candid-encoded and have an API character, while the second are JSON encoded and are an implementation detail (from the EVM-RPC canister point of view)
2. Copy over the full code of `EthRpcClient`.
4. Eliminate the dependency on `cketh_common`
