### ISSUE TITLE
When accessing a custom URL through evm_rpc, I receive the error HttpOutcallError(IcError { code: SysTransient, message: \"Connecting to node.dobno30489dlkwmd.info failed: Failed to directly connect: client error (Connect)\" })

### ISSUE THREAD

**Issue by Meet-King** [internet-computer-protocol/evm-rpc-canister#292]
When I start evm_rpc canister on my local dfx, everything works fine for calling nonce and sending transactions. But after deploying on IC, the same JSON-RPC call to fetch the nonce returns the error mentioned above. Both local and IC configurations are identical, and the node is a custom private chain, which works fine on local.

Can anyone help me?

**Comment by rvanasa** [comment]
Thank you for reaching out. What blockchain / network ID are you using for the request? If you can send an example dfx command, that would be helpful for us to reproduce the issue and understand what's happening.

**Comment by Meet-King** [comment]
The problem has been solved. The link of the node needs to support IPv6. Thank you for your reply
